PortalKorepetycyjny/Models/StudentAdvertisment.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace PortalKorepetycyjny.Models
{
    public class StudentAdvertisment
    {
        public int Id { get; set; }
        public string CreatorId { get; set; }
        public Subject SbujectName { get; set; }
        public string Descryption { get; set; }
        public string Title { get; set; }
        public DateTime AdvertismentDate { get; set; }



    }
}

PortalKorepetycyjny/Controllers/StudentAdvertismentsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using PortalKorepetycyjny.Models;
using PagedList;

namespace PortalKorepetycyjny.Controllers
{
    public class StudentAdvertismentsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: StudentAdvertisments
        public ActionResult Index(int page = 1)
        {
            if (Request.IsAjaxRequest())
            {
                return PartialView("_Advertisements", db.StudentAdvertisments.OrderBy(r => r.Title).ToPagedList(page, 10));
            }
            return View(db.StudentAdvertisments.OrderBy(r => r.Title).ToPagedList(page, 10));
        }

        // GET: StudentAdvertisments/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            StudentAdvertisment studentAdvertisment = db.StudentAdvertisments.Find(id);
            if (studentAdvertisment == null)
            {
                return HttpNotFound();
            }
            return View(studentAdvertisment);
        }

        // GET: StudentAdvertisments/Create
        public ActionResult Create()
        {
            //ViewData["Subjects"] = db.Subjects.Select(s => s.Name).ToList();
            List<SelectListItem> subjects = new List<SelectListItem>();
            foreach(var sub in db.Subjects)
            {
                subjects.Add(new SelectListItem { Text = sub.Name, Value = sub.Id.ToString() });
            }
            ViewBag.SbujectName = subjects;
            return View();
        }

        // POST: StudentAdvertisments/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult Create([Bind(Include = "Descryption,Title")] StudentAdvertisment studentAdvertisment,int SbujectName)
        {
            if (ModelState.IsValid)
            {
                studentAdvertisment.CreatorId = User.Identity.GetUserId();
                studentAdvertisment.AdvertismentDate = DateTime.Now;
                studentAdvertisment.SbujectName = db.Subjects.FirstOrDefault(s => s.Id == SbujectName);
                db.StudentAdvertisments.Add(studentAdvertisment);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View("Index");
        }

        // GET: StudentAdvertisments/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            StudentAdvertisment studentAdvertisment = db.StudentAdvertisments.Find(id);
            if (studentAdvertisment == null)
            {
                return HttpNotFound();
            }
            return View(studentAdvertisment);
        }

        // POST: StudentAdvertisments/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Descryption,Title,AdvertismentDate")] StudentAdvertisment studentAdvertisment)
        {
            if (ModelState.IsValid)
            {
                db.Entry(studentAdvertisment).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(studentAdvertisment);
        }

        // GET: StudentAdvertisments/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            StudentAdvertisment studentAdvertisment = db.StudentAdvertisments.Find(id);
            if (studentAdvertisment == null)
            {
                return HttpNotFound();
            }
            return View(studentAdvertisment);
        }

        // POST: StudentAdvertisments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            StudentAdvertisment studentAdvertisment = db.StudentAdvertisments.Find(id);
            db.StudentAdvertisments.Remove(studentAdvertisment);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

PortalKorepetycyjny/Views/StudentAdvertisments/Create.cshtml
@model PortalKorepetycyjny.Models.StudentAdvertisment

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>StudentAdvertisment</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Descryption, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Descryption, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Descryption, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SbujectName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("SbujectName")
                
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

PortalKorepetycyjny/Views/StudentAdvertisments/Delete.cshtml
@model PortalKorepetycyjny.Models.StudentAdvertisment

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>StudentAdvertisment</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Descryption)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Descryption)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AdvertismentDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AdvertismentDate)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

PortalKorepetycyjny/Views/StudentAdvertisments/Details.cshtml
@model PortalKorepetycyjny.Models.StudentAdvertisment

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>StudentAdvertisment</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Descryption)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Descryption)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AdvertismentDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AdvertismentDate)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

PortalKorepetycyjny/Views/StudentAdvertisments/Edit.cshtml
@model PortalKorepetycyjny.Models.StudentAdvertisment

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>StudentAdvertisment</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Descryption, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Descryption, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Descryption, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AdvertismentDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AdvertismentDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AdvertismentDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

PortalKorepetycyjny/Views/StudentAdvertisments/Index.cshtml
@model IEnumerable<PortalKorepetycyjny.Models.StudentAdvertisment>

@{
    ViewBag.Title = "Index";
}
@Styles.Render("~/Content/index")
<h3>Szukaj</h3>

<form method="get" action="@Url.Action("Index")"
      data-advertisement-ajax="true" data-advertisement-target="#advertisementList">
    <input type="search" name="searchTerm" />
    <input type="submit" value="Szukaj" />
</form>

@Html.Partial("_Advertisements", Model)

PortalKorepetycyjny/Views/StudentAdvertisments/_Advertisements.cshtml
@using PagedList
@using PagedList.Mvc
@using Microsoft.AspNet.Identity
@model IPagedList<PortalKorepetycyjny.Models.StudentAdvertisment>
<div id="productList">

    <div class="pagedList" data-advertisement-target="#advertisementList">
        @Html.PagedListPager(Model, page => Url.Action("Index", new { page }),
       PagedListRenderOptions.MinimalWithItemCountText)
    </div>
    <p>
        @Html.ActionLink("Create New", "Create")
    </p>

    <div class="container">
        <div class="iconcontainer">

            <div class="row">
                @foreach (var item in Model)
                {

                    <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
                        <div class="iconbox">
                            <div class="iconbox-icon">
                                <span class="glyphicon glyphicon-tasks"></span>
                            </div>
                            <div class="featureinfo">
                                <h4 class="text-center">@Html.DisplayFor(modelItem => item.Title)</h4>
                                <h5 class="text-center">@Html.DisplayFor(modelItem => item.AdvertismentDate)</h5>
                                <p>
                                    @Html.DisplayFor(modelItem => item.Descryption)
                                </p>

                                <a class="btn btn-default btn-sm" href="@Url.Action("Edit", "StudentAdvertisments", new { id = item.Id })" role="button">Edit</a>
                                <a class="btn btn-default btn-sm" href="@Url.Action("Delete", "StudentAdvertisment", new { id = item.Id })" role="button">Delete</a>
                               
                                <a class="btn btn-default btn-sm" href="@Url.Action("Details", "StudentAdvertisments", new { id = item.Id })" role="button">Details</a>
                            </div>
                        </div>
                    </div>



                }

            </div>
        </div>
    </div>
</div>