PortalKorepetycyjny/Controllers/AdvertismentsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using PortalKorepetycyjny.Models;
using PagedList;

namespace PortalKorepetycyjny.Controllers
{
    [Authorize]
    public class AdvertismentsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();


        // GET: Advertisments
        public ActionResult Index(int page = 1)
        {
            /*var currentUser = db.Coaches.Find(User.Identity.GetUserId());   //Jeśli użytkownik inny niż Coach to redirect na Home
            if(currentUser == null)
            {
                return Redirect("/home");
            }*/

            /*var model = (from a in db.Advertisments
                         join c in db.Coaches on a.CoachId equals c.Id
                         orderby a.Title
                        where a.CoachId == c.Id
                         select new AdvertisementDTO
                         {
                             Id = a.CoachId,
                             CoachNameAndSurname = c.Name + " " + c.Surname,
                             PublicationDate = a.PublicationDate,
                             Title = a.Title,
                             Description = a.Description
                         }).ToPagedList(page, 10);*/

            if (Request.IsAjaxRequest())
            {
                return PartialView("_Advertisements", db.Advertisments.OrderBy(r => r.Title).ToPagedList(page, 10));
            }
            return View(db.Advertisments.OrderBy(r => r.Title).ToPagedList(page, 10));
        }

        // GET: Advertisments/Details/5
        [Authorize]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Advertisment advertisment = db.Advertisments.Find(id);
            if (advertisment == null)
            {
                return HttpNotFound();
            }

            string currentId = id.ToString();

            var model = (from a in db.Advertisments
                         join c in db.Coaches on a.CoachId equals c.Id
                         orderby a.Title
                         where a.CoachId == currentId
                         select new AdvertisementDTO
                         {
                             Id = a.CoachId,
                             CoachNameAndSurname = c.Name + " " + c.Surname,
                             PublicationDate = a.PublicationDate,
                             Title = a.Title,
                             Description = a.Description
                         });

            //return View(model);

            return View(advertisment);
        }

        // GET: Advertisments/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Advertisments/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult Create([Bind(Include = "Title,Description")] Advertisment advertisment)
        {
            if (ModelState.IsValid )
            {

                advertisment.CoachId = User.Identity.GetUserId();
                advertisment.PublicationDate = DateTime.Now;
                db.Advertisments.Add(advertisment);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(advertisment);
        }

        // GET: Advertisments/Edit/5
        [Authorize]
        public ActionResult Edit(int? id)
        {
            var loggedInUser = User.Identity.GetUserId();

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Advertisment advertisment = db.Advertisments.Find(id);
            if (advertisment == null)
            {
                return HttpNotFound();
            }
            

            if(advertisment.CoachId!= loggedInUser)
            {
                return new HttpStatusCodeResult(HttpStatusCode.Forbidden);
            }
            else {
                return View(advertisment);

            }
            

        }

        // POST: Advertisments/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,CoachId,Title,PublicationDate,Description")] Advertisment advertisment)
        {
            if (ModelState.IsValid)
            {
                db.Entry(advertisment).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(advertisment);
        }


        // GET: Advertisments/Delete/5
        [Authorize]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Advertisment advertisment = db.Advertisments.Find(id);
            var loggedInUser = User.Identity.GetUserId();

            if (advertisment.CoachId != loggedInUser)
            {
                return new HttpStatusCodeResult(HttpStatusCode.Forbidden);
            }
            else
            {
                return View(advertisment);

            }
            if (advertisment == null)
            {
                return HttpNotFound();
            }
            return View(advertisment);
        }

        // POST: Advertisments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult DeleteConfirmed(int id)
        {
            Advertisment advertisment = db.Advertisments.Find(id);
            db.Advertisments.Remove(advertisment);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

PortalKorepetycyjny/Controllers/HomeController.cs
using PagedList;
using PortalKorepetycyjny.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PortalKorepetycyjny.Controllers
{
    public class HomeController : Controller
    {
        ApplicationDbContext db = new ApplicationDbContext();

        public ActionResult Index(string searchTerm, int page = 1)
        {
            /*var model = db.Advertisments
                .OrderBy(r => r.PublicationDate)
                .Where(r => searchTerm == null || r.Description.Contains(searchTerm))
                .Select(r => new AdvertisementDTO
                {
                    Id = r.CoachId,
                    CoachNameAndSurname = r.Coach.Name + " " + r.Coach.Surname,
                    Title = r.Title,
                    Description = r.Description
                }).ToPagedList(page, 10);*/

            /*var model = (from a in db.Advertisments
                         join c in db.Coaches on a.CoachId equals c.Id
                         orderby a.Title
                        where a.CoachId == c.Id
                         select new AdvertisementDTO
                         {
                             Id = a.CoachId,
                             CoachNameAndSurname = c.Name + " " + c.Surname,
                             PublicationDate = a.PublicationDate,
                             Title = a.Title,
                             Description = a.Description
                         }).ToPagedList(page, 10);*/

            if (Request.IsAjaxRequest())
            {
                return PartialView("_Advertisements", db.Advertisments.OrderBy(r => r.Title).ToPagedList(page,10));
            }
            return View(db.Advertisments.OrderBy(r => r.Title).ToPagedList(page,10));
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

PortalKorepetycyjny/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>Witamy w korepetytex</h3>

<p>To jest nasza strona z korepetycjami</p>

PortalKorepetycyjny/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    Polibuda<br />
    Białystok, WA 98052-6399<br />
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">korepetytex@asdf.pl</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">korepetytex@asdf.pl</a>
</address>

PortalKorepetycyjny/Views/Home/Index.cshtml
@model IEnumerable<PortalKorepetycyjny.Models.Advertisment>

@{
    ViewBag.Title = "Home Page";
}
@Styles.Render("~/Content/index")

<h3>Szukaj</h3>

<form method="get" action="@Url.Action("Index")"
      data-advertisement-ajax="true" data-advertisement-target="#advertisementList">
    <input type="search" name="searchTerm" />
    <input type="submit" value="Szukaj" />
</form>

@Html.Partial("_Advertisements", Model)

PortalKorepetycyjny/Views/Home/_Advertisements - Copy.cshtml
@using PagedList
@using PagedList.Mvc
@using Microsoft.AspNet.Identity
@model IPagedList<PortalKorepetycyjny.Models.Advertisment>
<div id="productList">

    <div class="pagedList" data-advertisement-target="#advertisementList">
        @Html.PagedListPager(Model, page => Url.Action("Index", new { page }),
       PagedListRenderOptions.MinimalWithItemCountText)
    </div>
    <p>
        @Html.ActionLink("Create New", "Create", "Advertisments")
    </p>

    <table class="table">
        <tr>
            <th>
                Imie i nazwisko
            </th>
            <th>
                Tytuł
            </th>
            <th>
                Opis
            </th>
        </tr>



        @foreach (var item in Model)
        {
            string text = item.Coach.Name + " " + item.Coach.Surname;

            <tr>
                <td>
                    @Html.DisplayFor(modelItem => text)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Title)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
                <td>
                    @if (User.Identity.GetUserId() == item.CoachId)
                    {
                        @Html.ActionLink("Edit", "Edit", "Advertisments", new { id = item.Id }, null)
                        @Html.ActionLink("Delete", "Delete", "Advertisments", new { id = item.Id }, null)
                    }

                    @Html.ActionLink("Details", "Details", "Advertisments", new { id = item.Id }, null)
                </td>
            </tr>
        }
    </table>
</div>

PortalKorepetycyjny/Views/Home/_Advertisements.cshtml
@using PagedList
@using PagedList.Mvc
@using Microsoft.AspNet.Identity
@model IPagedList<PortalKorepetycyjny.Models.Advertisment>
<div id="productList">

    <div class="pagedList" data-advertisement-target="#advertisementList">
        @Html.PagedListPager(Model, page => Url.Action("Index", new { page }),
       PagedListRenderOptions.MinimalWithItemCountText)
    </div>
    <p>
        @Html.ActionLink("Create New", "Create", "Advertisments")
    </p>

    <div class="container">
        <div class="iconcontainer">

            <div class="row">
                @foreach (var item in Model)
                {
                    string text = item.Coach.Name + " " + item.Coach.Surname;


                    <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
                        <div class="iconbox">
                            <div class="iconbox-icon">
                                <span class="glyphicon glyphicon-book"></span>
                            </div>
                            <div class="featureinfo">
                                <h4 class="text-center">@Html.DisplayFor(modelItem => item.Title)</h4>
                                <h5 class="text-center">@Html.DisplayFor(modelItem => text)</h5>
                                <p>
                                    @Html.DisplayFor(modelItem => item.Description)
                                </p>

                                @if (User.Identity.GetUserId() == item.CoachId)
                                {
                                    <a class="btn btn-default btn-sm" href="@Url.Action("Edit", "Advertisments", new { id = item.Id })" role="button">Edit</a>
                                    <a class="btn btn-default btn-sm" href="@Url.Action("Delete", "Advertisment", new { id = item.Id })" role="button">Delete</a>

                                }

                                <a class="btn btn-default btn-sm" href="@Url.Action("Details", "Advertisments", new { id = item.Id })" role="button">Details</a>
                            </div>
                        </div>
                    </div>



                }
             
            </div>
        </div>
    </div>
</div>